<?php

namespace FootBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends EntityRepository
{

    public function getPlaiedMatch($equipe,$type)
    {
        $now = new \DateTime('now');
        $qb = $this->createQueryBuilder('m')
                ->where('m.equipe = :equipe')
                ->andWhere('m.date <= :now')
                ->andWhere('m.typematch = :type')
                ->setParameter('equipe', $equipe)
                ->setParameter('now', $now)
                ->setParameter('type', $type);

        return $qb->getQuery()->getResult();
    }
    
    public function nbTotal($equipe,$type)
    {
        $qb = $this->createQueryBuilder('m')
                ->select('count(m.id)')
                ->where('m.equipe = :equipe')
                ->andWhere('m.typematch = :type')
                ->setParameter('equipe', $equipe)
                ->setParameter('type', $type);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
